name: Send highlight of the day

on:
  # schedule:
  #   - cron: '0 16 * * *'
  push:
    branches:
      - master

jobs:
  send_highlight:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: prepare email
        run: |
          ls -la
          python .github/highlight_generator.py

      - name: send email
        uses: dawidd6/action-send-mail@v3
        env:
          To: "vgnshiyer@asu.edu"
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.EMAILPASSWORD }}
          subject: Highlight of the day
          html_body: file://.github/output.html
          to: ${{ env.To }}
          from: ${{ secrets.EMAIL }}
          content_type: text/html
